[tool.poetry]
name = "open-rarity"
version = "0.1.0"
description = "Open-Rarity library is an open standard that provides an easy , explanable and reproducible computation for NFT rarity"
authors = ["Dan Meshkov <daniil.meshkov@opensea.io>"]
license = "MIT"

[tool.poetry.dependencies]
numpy = "^1.21.4"
pandas = "^1.3.5"
python = ">=3.10,<3.11"
pre-commit = "^2.19.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | venv
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
target_version = ['py310']

[tool.isort]
include_trailing_comma = true
known_first_party = "openrarity"
multi_line_output = 3
profile = "black"
