[tool.poetry]
name = "open-rarity"
version = "0.1.0"
description = "Open-Rarity library is an open standard that provides an easy , explanable and reproducible computation for NFT rarity"
authors = ["Dan Meshkov <daniil.meshkov@opensea.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
