name: "Setup Python"
description: "Setup Python using Poetry, install dependencies, and properly caches environment between re-runs"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10.3"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
