name: Build
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-actions

  unit-tests:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: ./.github/actions/setup-actions

      - name: Unit tests
        run: poetry run python pytest
