name: Formatting and unit tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Install Nox
        uses: wntrblm/nox@2023.04.22
        with:
          python-versions: "3.10,3.11"

      - name: Linter
        uses: py-actions/flake8@v2

      - name: Code Formatting
        uses: psf/black@stable

      - name: Type Check
        run: |
          pip install poetry
          poetry install
          poetry run mypy open_rarity

      - name: Unit tests
        run: nox
